language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  # Install self (we are required for some of our own dev reqs for now)
  # NOTE: *do not* use -e as it adds checkout root to sys.path, which prevents
  # us from having a "pure" install environment like a new user would have.
  # E.g. it makes our internal test module importable :(
  - pip install .
  # Pre-requirements sanity test (again, resembles pure, non-dev install
  # environment.) Avoids e.g. spec's 'six' from gumming up our attempts to
  # import our vendorized 'six'.
  - pip install -r tasks-requirements.txt
  - inv --list
  # Install remaining dev requirements (test runner, etc)
  - pip install -r dev-requirements.txt
script:
  - inv test
  - inv docs
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    on_success: change
    on_failure: change
  email: false
