language: python
sudo: required
# travis changes on 2017.06.21 appear to have broken pypy, causing attemtped
# downloads of "-.tar.bz2" (resulting in 'bzip2: (stdin) is not a bzip2 file.')
# (same changes MIGHT also have gotten a version of CPython 3.6 exhibiting
# https://bugs.python.org/issue29167; at least, that bug is definitely
# appearing.)
# Pinning to previous travis image for now.
group: deprecated-2017Q2
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See #358.
  # Additionally, -dev/-nightly builds may be unstable; we do not want them
  # marking our own tests as outright failures.
  allow_failures:
    - python: "pypy3"
    - python: "3.7-dev"
    - python: "nightly"
  # Disabled per https://github.com/travis-ci/travis-ci/issues/1696
  # fast_finish: true
install:
  # For some reason Travis' build envs have wildly different pip/setuptools
  # versions between minor Python versions, and this can cause many hilarious
  # corner packaging cases. So...
  - pip install -U pip
  # Setuptools 34+ seems to get less stable
  - pip install 'setuptools>33,<34'
  # Pre-requirements sanity test (again, resembles pure, non-dev install
  # environment.) Avoids e.g. spec's 'six' from gumming up our attempts to
  # import our vendorized 'six'.
  - pip install -r tasks-requirements.txt
  - inv --list
  # Install remaining dev requirements (test runner, etc)
  - pip install -r dev-requirements.txt
  - pip list --format=columns
  # Also create a workable alt-interpreter venv for testing dual package builds
  # Python 3 is nicely namespaced, globally. Python 2 is masked by Travis'
  # default venv, so we gotta hardcode it.
  - "virtualenv alt_env --python=$([[ $TRAVIS_PYTHON_VERSION == 2* ]] && echo python3 || echo /usr/bin/python)"
  - alt_env/bin/pip install wheel
before_script:
  # Create 'sudouser' w/ sudo password & perms on Travis' homedir
  - inv travis.make-sudouser
script:
  # Execute full test suite + coverage, as the new sudo-capable user
  - inv travis.sudo-coverage
  # Websites build OK? (Not on PyPy3, Sphinx is all "who the hell are you?" =/
  - "[[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]] && inv sites"
  # Doctests in websites OK?
  - inv www.doctest
  # Did we break setup.py?
  - inv travis.test-installation --package=invoke --sanity="inv --list"
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
  # Test distribution builds.
  - inv travis.test-packaging --package=invoke --sanity="inv --list" --alt-python=alt_env/bin/python
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    template:
      - "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    on_error: change
  email: false
