language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  # pypy is frequentlyish unstable on Travis, don't let it mark entire status
  # as 'bad' =/ (Still worth running it though.)
  allow_failures:
    - python: pypy
    - python: pypy3
install:
  # Pre-requirements sanity test (again, resembles pure, non-dev install
  # environment.) Avoids e.g. spec's 'six' from gumming up our attempts to
  # import our vendorized 'six'.
  - pip install -r tasks-requirements.txt
  - inv --list
  # Install remaining dev requirements (test runner, etc)
  - pip install -r dev-requirements.txt
script:
  # Run unit and integration tests, generating coverage report (skipping html)
  # This will fail if the tests fail.
  - "inv coverage --no-html"
  # Websites build OK?
  - inv sites
  # Did we break setup.py?
  - pip uninstall -y invoke # To undo the implicit -e install from above
  - pip install . # NO -e!
  - inv -l # Sanity check
  # Did we break actual dist archive generation?
  - inv release.build
  - pip uninstall -y invoke
  - "pip install dist/*.whl"
  - inv -l
  - pip uninstall -y invoke
  - "pip install dist/*.tar.gz"
  - inv -l
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
