language: python
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See #358.
  allow_failures:
    - python: pypy3
  fast_finish: true
install:
  # Pre-requirements sanity test (again, resembles pure, non-dev install
  # environment.) Avoids e.g. spec's 'six' from gumming up our attempts to
  # import our vendorized 'six'.
  - pip install -r tasks-requirements.txt
  - inv --list
  # Install remaining dev requirements (test runner, etc)
  - pip install -r dev-requirements.txt
  # Also create a workable alt-interpreter venv for testing dual package builds
  # Python 3 is nicely namespaced, globally. Python 2 is masked by Travis'
  # default venv, so we gotta hardcode it.
  - "virtualenv alt_env --python=$([[ $TRAVIS_PYTHON_VERSION == 2* ]] && echo python3 || echo /usr/bin/python)"
  - alt_env/bin/pip install wheel
before_script:
  # Make sudo user for running tests (as tests care about sudo)
  - inv travis.make_sudouser
script:
  # Execute full test suite + coverage, as the new sudo-capable user
  - inv travis.sudo_coverage
  # Websites build OK? (Not on PyPy3, Sphinx is all "who the hell are you?" =/
  - "[[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]] && inv sites"
  # Doctests in websites OK?
  - inv www.doctest
  # Did we break setup.py?
  - inv travis.test_installation --package=invoke --sanity="inv --list"
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
  # Test distribution builds, including our custom dual wheel BS
  - inv travis.test_packaging --package=invoke --sanity="inv -l" --alt-python=alt_env/bin/python
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
